apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: true
    jsonData:
      version: Flux
      organization: pi_server
      defaultBucket: sensor_data
      tlsSkipVerify: false
    secureJsonData:
      token: my-super-secret-admin-token
